### ISSUE TITLE
perl needed?

### ISSUE THREAD

**Issue by jbergstroem** [gavinzhou/alpine-kong#2]
I tried removing perl from dependencies and the image built successfully. Is it really needed? Seems to remove ~45mb from the image size.

**Comment by gavinzhou** [comment]
@jbergstroem 

kong start need with restry

https://github.com/Mashape/kong/blob/master/bin/kong#L1

restry is perl base

https://github.com/openresty/resty-cli/blob/master/bin/resty#L1

I build kong without perl 
I get error msg

```
env: can't execute 'perl':
```

**Comment by jbergstroem** [comment]
ahh; sorry -- I'm just getting acquainted with it. I wonder if resty is really necessary here; I know a lot of people running bare metal openresty avoids it. Will investigate and open a new pr/issue if i find a better solution. Thanks for your feedback.
